### ISSUE TITLE
limit without offset does not work

### ISSUE THREAD

**Issue by davelandry** [Datawheel/mondrian-rest-client#16]
Currently, in order to limit a query without an offset, users must type this:

```js
query.pagination(limit, "0");
```

This is because at [this line](https://github.com/Datawheel/mondrian-rest-client/blob/master/src/query.ts#L122), `offset` is falsey, so it falls back to `undefined`, but in order to limit in mondrian-rest an offset must be defined in the query. That line would probably have to change to this:

```js
this.offset = offset || 0;
```

**Comment by frabarz** [comment]
closed on d893b8aa1a630a4a0777f3d4a73bf7ffd14fdef4
